title: EKA2L1 - Symbian OS Emulator/N-Gage emulator
email: cc@12l1.com
description:
  A Symbian OS Emulator/N-Gage emulator
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://12l1.com"
github_username:  EKA2L1

languages: [ "en", "vi", "es", "pt-br", "ru", "zh-cn", "it" ]
exclude_from_localization: ["assets", "CNAME"]
defaultLang: en
languageNames:
  en: English
  zh-cn: 简体中文
  vi: Tiếng Việt
  es: Español
  pt-br: Português
  ru: Русский
  it: Italiano

theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
   
footer:
  links:
    - label: Github
      icon: "fab fa-fw fa-github"
      url: "https://github.com/eka2l1/eka2l1"
    - label: Discord
      icon: "fab fa-discord"
      url: "https://discord.gg/5Bm5SJ9"
    - label: Youtube
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/channel/UCCdPQT6Le2xw_z9cutkVwyA"
    - label: Mail
      icon: "fas fa-envelope"
      url: "mailto:cc@12l1.com"
    - label: Website source
      icon: "fa fa-globe"
      url: "https://github.com/EKA2L1/eka2l1.github.io"

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
